repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.10.0"
    hooks:
      - id: mypy
        args: [--no-strict-optional, --install-types, --non-interactive, --ignore-missing-imports]
        stages: [pre-commit]
exclude: "tests"
